FROM ghcr.io/cargo-lambda/cargo-lambda:latest

# Install dependencies, including OpenSSL for the target architecture
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev m4 && \
    apt-get clean

# Set the working directory
WORKDIR /app

# Set the default command to run when the container starts
ENTRYPOINT ["cargo", "build"]
