[package]
name = "critical_zoomer-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rug = "1.27.0"

[dependencies.critical_zoomer]
path = ".."

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_range"
path = "fuzz_targets/fuzz_range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_coords_parse"
path = "fuzz_targets/fuzz_coords_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_publisher_clamp"
path = "fuzz_targets/fuzz_publisher_clamp.rs"
test = false
doc = false
bench = false
